/** Shared command inventory: help must never start a model, server, or wizard. */
export const COMMAND_HELP: Record<string, string> = {
  setup: 'grain setup\nConfigure providers, memory, and workspace defaults interactively. Alias: init.',
  init: 'grain init\nAlias for grain setup.',
  update: 'grain update [--check] [--yes] [--source PATH | --release]\nCheck/install a verified release, or rebuild a local source checkout.\nSource mode never pulls or switches your branch. The previous binary is backed up.\nNpm installations: npm install -g grain@latest.',
  config: 'grain config [show|set KEY VALUE|reset]\nInspect or edit Grain configuration. Reset restores defaults.',
  status: 'grain status\nInspect the current workspace, provider configuration, and optional memory service.',
  doctor: 'grain doctor\nCheck configuration, agents, executors, Git, and optional Engram.',
  skills: 'grain skills [list|validate|view NAME|add NAME|delete NAME]\nAdd opens an interactive editor; validate checks portable SKILL.md packages.\nInstall packages in $GRAIN_HOME/skills/NAME/SKILL.md (default ~/.grain).\nProject skills: .grain/skills/NAME/SKILL.md. Delete only removes user-owned skills.',
  mcp: 'grain mcp [list|validate|tools SERVER]\nList/validate $GRAIN_HOME/mcp.json without connecting.\nTools connects to one explicitly enabled server and shows allowed/blocked tools.\nConfigure servers with stdio command/args or HTTP url and trust.enabled/allowTools.',
  memory: 'grain memory [status|stats|search QUERY|list|add FACT|get ID|edit ID TEXT|delete ID|export|rebuild]\nOptional Engram memory service. Alias: engram.',
  engram: 'grain engram [status|stats|search QUERY|list|add FACT|get ID|edit ID TEXT|delete ID|export|rebuild]\nAlias: grain memory. Engram must be available for memory operations.',
  wiki: 'grain wiki build|sync|search QUERY|show ID|verify [ID]|diff|serve\nBuild and inspect source-derived repository documentation. Serve starts a local viewer.',
  runs: 'grain runs [list|inspect ID|replay ID|events ID|context ID|export ID PATH]\nInspect durable local run journals.',
  learning: 'grain learning [list|show ID|propose STATEMENT [RUN]|validate ID RUN|promote ID|migrate SCOPE]\nInspect and govern learned evidence.',
  agents: 'grain agents [list|profiles|validate|run PROFILE OBJECTIVE|show ID|dashboard ID|watch ID|execute ID|merge ID|cancel GRAPH TASK]\nCreate a graph: grain agents solo|pair|research|plan|swarm|review-panel|repair-loop|migration-loop|benchmark-loop|recursive-delivery OBJECTIVE\nExecuting agents may modify workspaces and invoke configured models.',
  jobs: 'grain jobs [list|add NAME CRON -- TASK|remove NAME|enable NAME|disable NAME|run NAME|run-due]\nManage scheduled tasks. Example: grain jobs add review @daily -- Review my notes',
  daemon: 'grain daemon [status|start|run|stop|logs|install]\nSupervise scheduled jobs; install prints service configuration.',
  note: 'grain note "TEXT"\nSave a durable note in the current project.',
  worklog: 'grain worklog [--limit N] [--verbose]\nShow the current project work record.',
  recall: 'grain recall "QUERY" [--all]\nSearch project notes and work records; --all spans repositories.',
  tui: 'grain tui [--run ID|--resume ID]\nOpen the scrolling terminal or inspect a recorded run.',
  lab: 'grain lab [--run ID]\nStart the local run-inspection web server.',
  serve: 'grain serve is unavailable. Use grain for terminal work, grain lab for runs, or grain wiki serve for documentation.',
  version: 'grain version\nPrint the installed version. Alias: --version.',
};
